# Generated by Django 4.1.5 on 2023-02-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='produkt',
            new_name='product',
        ),
    ]
